### ISSUE TITLE
How to set the duration of the animation?

### ISSUE THREAD

**Issue by luis-cruzt** [federicoviceconti/card_stack_widget#1]
Hello!

Awesome package, but is there anyway to modify the duration of the animation? It's changing between items too fast

**Comment by federicoviceconti** [comment]
Hi, thanks for the feedback!

Are you talking about the dismiss animation?

**Comment by luis-cruzt** [comment]
Yeah it seems too fast and it would be great to set the duration to make it look smoother
![image](https://user-images.githubusercontent.com/55716036/215601181-14c34174-fe4c-4042-bbd0-72366b23672b.png)

**Comment by federicoviceconti** [comment]
Hi, can this work?

I will add an external parameter for duration.

![gif](https://user-images.githubusercontent.com/25590766/216579765-555fcf21-8ea7-4640-9a5f-8687a49f5dbb.gif)

**Comment by federicoviceconti** [comment]
Available on v1.0.5.
