### ISSUE TITLE
add reverseSize like this

### ISSUE THREAD

**Issue by Keekuun** [federicoviceconti/card_stack_widget#3]
![image](https://github.com/user-attachments/assets/db708196-239a-46a1-b20e-feb4c79b2929)

**Comment by Keekuun** [comment]
example: https://github.com/[Keekuun/card_stack_widget_new](https://github.com/Keekuun/card_stack_widget_new)

**Comment by federicoviceconti** [comment]
@Keekuun feel free to open a new PR. Closing this issue for now.
